### ISSUE TITLE
uninitialized constant JbuilderTemplate (NameError)

### ISSUE THREAD

**Issue by fridgerator** [yonahforst/jbuilder_cache_multi#13]
```
/.rvm/gems/ruby-2.2.2@oxford-cms/gems/jbuilder_cache_multi-0.0.3/lib/jbuilder_cache_multi/jbuilder_ext.rb:1:in `<top (required)>': uninitialized constant JbuilderTemplate (NameError)
```

from Gemfile.lock

```
jbuilder (2.3.2)
  activesupport (>= 3.0.0, < 5)
  multi_json (~> 1.2)
jbuilder_cache_multi (0.0.3)
 jbuilder (>= 1.5.0, < 3)
```

**Comment by noiseunion** [comment]
I am seeing this same error on Ruby 2.2.1 - @fridgamarator were you able to resolve this?

**Comment by fridgamarator** [comment]
@noiseunion no, I didn't spend too much time on it

**Comment by noiseunion** [comment]
@fridgamarator Thanks for the response.  If I get time, I'll take a look.

**Comment by orhantoy** [comment]
@fridgamarator Had the same issue - placing `gem 'jbuilder_cache_multi'` after `gem 'jbuilder'` (in the Gemfile) resolved it for me.
