### ISSUE TITLE
broken with rails 5

### ISSUE THREAD

**Issue by woodhull** [yonahforst/jbuilder_cache_multi#16]
Under rails 5 this gem the example code raises with

`ActionView::Template::Error: unknown keyword: expires_in`

**Comment by jdelStrother** [comment]
@woodhull could you give #18 a try?

**Comment by woodhull** [comment]
We stopped using the gem.

**Comment by yonahforst** [comment]
@jdelStrother - I just merged your PR. Thanks so much for sending it. I haven't been working on RoR projects lately and couldn't find the time to bring myself up to speed.
