### ISSUE TITLE
New version on rubygems

### ISSUE THREAD

**Issue by aserafin** [yonahforst/jbuilder_cache_multi#17]
Hey, 

Do you think you could push latest master to rubygems? Especially having correct key generation on rubygems would be important.

**Comment by markwpiper** [comment]
+1  There is a critical bug in the 0.0.3 version released on RubyGems where cache key generation is not correct.   Please update RubyGems, or add a warning to not use it!

Specifically, when using a proc for key generation, the proc is only used on the first item in the collection; the subsequent items have incorrect keys generated for them.

**Comment by yonahforst** [comment]
sorry for the late reply to this. i havent been working on Ror projects lately. I just pushed version 0.1.0 to rubygems
